/*
 * FindTheDifference.c
 *
 *  Created on: Sep 29, 2016
 *      Author: xinsu
 *
 * Assume the inputs are all lowercase letters
 */

/*
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */

#include <stdio.h>

char findTheDifference(char* s, char* t) {
	char result = NULL;

	int i = 0;
	while (s[i] != '\0') {
		result ^= s[i] ^ t[i++];
	}
	result ^= t[i];

	return result;
}

